include = '/etc/postgresql/pgaudit.conf'
# pgAudit
shared_preload_libraries = 'pgaudit'
pgaudit.log = 'read,write,ddl,role'
pgaudit.role = 'pgaudit_auditor'
pgaudit.log_relation = on
pgaudit.log_parameter = off

# Connection logging
log_connections = on
log_disconnections = on

# Log files
logging_collector = on
log_destination = 'stderr'
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d.log'

# Daily rotation
log_rotation_age = '1d'
log_truncate_on_rotation = on